Repository add-ons/plugin.audio.vrt.radio, pull requests merged in 2020-06, with the labels that each got.

#18 Add IPTV Manager to settings
  resources/language/resource.language.en_gb/strings.po
  resources/settings.xml
Labels: enhancement

#19 Prepare for v0.1.2 release
  README.md
  addon.xml
Labels: release

#20 Fix data transfers over 1 MB to IPTV Manager
  resources/lib/iptvmanager.py
Labels: bug
